theme: minima
minima:
  skin: solarized

url: 'https://lauraporta.github.io/' 
baseurl: 'blog/' 

title: Personal Blog
author:
  name: lauraporta

description: >
  A blog about my ideas and thoughts on technology, art and more.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
